
#mybatis
mybatis:
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    auto-mapping-behavior: full

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true


spring:
  #mysql数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false&
    username: root
    password: root
  #springsecurity配置
  security:
    user:
      name: lmy
      password: lmy.123
  # spring整合redis配置
  redis:
    database: 0
    host: 172.20.10.128
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 3
#        max-wait: -1
        min-idle: 0
#    timeout: 1000

#加密参数
#秘钥
aes:
  sKey: "0CoJUm6Qyw8W8jud"
  #偏移量(十六位）
  ivParameter: "0102030405060708"
  #分隔符
  sp: "%%%"

#logging配置方式一，方式二在logback-spring.xml
logging:
  pattern:
#    console: "%d - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n"
    level: debug
  file:
    path: D:\develop\springboot\logs\springboot.log

# 启动端口
server:
  port: 8888
