
#mybatis
mybatis:
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true


spring:
  #mysql数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #springsecurity配置
  security:
    user:
      name: lmy
      password: lmy.123

#logging配置方式一，方式二在logback-spring.xml
logging:
  pattern:
#    console: "%d - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n"
    level: debug
  file:
    path: D:\develop\springboot\logs\springboot.log


